### ISSUE TITLE
Error changing the locale

### ISSUE THREAD

**Issue by esfoliante** [beinoriusju/TavoCalendar#14]
I am using your great calendar library for a project and it's been a great experience.
However, **I have been having some trouble changing the locale.**

I took a look at the source code of the moment.js library to try and find the correct locale for "Portuguese" but **when I change it, even in the file TavoCalendar.js, it doesn't update.**

Here's my code:

<a href="https://ibb.co/YQHBgsS"><img src="https://i.ibb.co/T29My3G/carbon-2.png" alt="carbon-2" border="0"></a>

**Comment by beinoriusju** [comment]
Have you included a PT-BR moment file that comes separate Meaning you have to include 3 files in total moment.js moment-pt-br.js and TavoCalendar. Let me know if that solved your problem.

**Comment by esfoliante** [comment]
Apparently, the mistake was mine, as my imports were wrong.
I looked it up from more sources about momentjs and found another link to the CDN.

Thanks for the help!
