### ISSUE TITLE
Week displacement depending on the locale

### ISSUE THREAD

**Issue by Ferboyy** [beinoriusju/TavoCalendar#15]
It seems that every locale whose week doesn't start with Sunday (for instance 'es', which starts with Monday), the last week of the month always shows a displacement towards the right:
![image](https://user-images.githubusercontent.com/84267263/118391540-08144480-b635-11eb-8718-2e7182e478b4.png)

I believe it's due to the week generation, where by default Sunday comes first. Is there any way to adjust it?

**Comment by beinoriusju** [comment]
I've released an update that fixes your problem.

**Comment by Ferboyy** [comment]
> I've released an update that fixes your problem.

Thank you! I can confirm that this issue is now resolved and works perfectly with the default config as well as with my own :
![image](https://user-images.githubusercontent.com/84267263/119263438-5306fc80-bbdf-11eb-9e1a-de08d29e34a8.png)
