### ISSUE TITLE
Moving ToDo

### ISSUE THREAD

**Issue by euaaron** [beinoriusju/TavoCalendar#2]
Hi @beinoriusju, I took the liberty to put your ToDo list here with the issues, so it will be easier to track their completion and also show the progress to you and the community. I will also try to do some of the items from your list. 

I've never collaborated with any project, and I don't know what I can do, so I just forked your repo.
I'm doing this because I'm using your calendar on a webpage and found that would be interesting to test my javascript skills by helping something that I already use to be greater. Hope I'm not doing something wrong.

**Comment by beinoriusju** [comment]
All good you have a green light here.
